### ISSUE TITLE
Cannot import library 'tensorflow'

### ISSUE THREAD

**Issue by florisvanlaarhoven** [janboone/msc_datascience#10]
Hi,

As opposed to the past weeks, I cannot manage to run the second cell (the one in which we import all libraries needed) in the notebook. It gives me the following error:

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-2f4caaa0de75> in <module>
      7 import statsmodels.formula.api as smf
      8 import matplotlib.pyplot as plt
----> 9 import tensorflow as tf
     10 import altair as alt
     11 from linearmodels.iv import IV2SLS

ModuleNotFoundError: No module named 'tensorflow'

I did not encounter this problem during the past weeks. Do you have any idea how to solve it?

Thank you in advance,

Floris

**Comment by janboone** [comment]
I will ask IT what is going on. tensorflow does seem to be installed, but python does not find it.

What helped in my case was from the File menu: close and shutdown notebook (save your notebook first, if necessary); and then open the notebook again.

Let me know whether this solves it in your case. (I still get an error for linearmodels, but at least you can continue with tensorflow)

**Comment by lindapelzer** [comment]
Hi! I encounter the same problem so maybe indeed it is a more general problem. Running the first cell also gives the following:

ERROR: Could not find a version that satisfies the requirement tensorflow==2.0.0-alpha0
ERROR: No matching distribution found for tensorflow==2.0.0-alpha0

Maybe because tenserflow is already installed, but installing linearmodels again does work. I don't know if this is causing the trouble?

**Comment by janboone** [comment]
installing tensorflow is easier now (than when I made the notebook). I think 

```
%%bash

pip install --user tensorflow
```

should work.

**Comment by lindapelzer** [comment]
Unfortunately, it returns the following error:

CalledProcessError: Command 'b'pip install --user tensorflow\n'' returned non-zero exit status 137.

**Comment by janboone** [comment]
that seems an odd error. Just to be sure: in the notebook, you create a new python code block. This code block starts with `%%bash` and on the next line (in the same code block) we have `pip install --user tensorflow`?

**Comment by lindapelzer** [comment]
Yes, that is what I did. Also tried to restart the kernel and run it, as well as in a new notebook.

**Comment by janboone** [comment]
can you send me an email with the web address of your jupyter notebook (the address in the browser when you work on jupyter lab)? (better not put this on github)

Then I will check your notebook myself to see what happens.

**Comment by MargotWolsink** [comment]
Hi,

I am having the same issues as Floris and Linda, so I was wondering if there was already a solution?

**Comment by janboone** [comment]
can you send me an email with the web address of your jupyter notebook (the address in the browser when you work on jupyter lab)? (better not put this on github)

Then I will check your notebook myself to see what happens.
