### ISSUE TITLE
Error mlp

### ISSUE THREAD

**Issue by lindapelzer** [janboone/msc_datascience#11]
Hi. I was going through the notebook again, and when training the multi-layer perceptron with

net = mlp(train,traint,5,outtype='logistic')
net.earlystopping(train,traint,valid,validt,0.1)
net.confmat(test,testt)

I get the following error:

 'module' object is not callable

From the issues on StackOverflow, I understand I am calling the 'module' mlp rather than the class. However, also with 'import mlp as mlp' or 'from mlp import mlp' I get the same.
Do you know how to fix this?

**Comment by janboone** [comment]
just to be sure: did you run the first code block in this section Multi-layer perceptron? That code block defines the class `mlp`. Once this is defined, there is no need to import it.

**Comment by lindapelzer** [comment]
Yes it worked! Also had some typos due to things I tried, but work now. Thanks.
