### ISSUE TITLE
Topic for the Assignment

### ISSUE THREAD

**Issue by brunoeduardosep** [janboone/msc_datascience#13]
Hello!
I wanted to ask if you think it is doable to replicate this thesis:

https://research.tilburguniversity.edu/en/publications/automatic-emotion-recognition-from-mandarin-speech

It uses PCA, and deep learning. 
I was thinking using DML instead of PCA for the features selection.

**Comment by janboone** [comment]
this would indeed be rather ambitious; e.g. in the course we did not look at speech at all. do they actually share their data?

**Comment by brunoeduardosep** [comment]
Sadly their data is not available =(
I find this topic really interesting.

**Comment by janboone** [comment]
indeed, too bad the data is not available.
