### ISSUE TITLE
Question regarding data selection

### ISSUE THREAD

**Issue by IvovanZitteren** [janboone/msc_datascience#14]
Hi, I was wondering if you could help me with the following question as an extensive Google search did not give me the answer I am looking for. My dataset consists of a combination of two databases. One database consists of individual-level data on the characteristics and compensation of the top five executive officers of big American companies. The second database consists of balance sheet information on the companies of these executives. I use 4 individual-specific variables (e.g. executive age) from the first database and about 15 to 20 company-specific variables from the second database (e.g. total company profit). This means that for executives of the same company, only 4 variables are unique to the specific executive and all company-specific variables are the exact same for all 5 executives. I want to use XGboost to predict executive compensation using these individual-specific and company-specific variables. Is it okay to use 5 executives from the same company or should I use only 1 executive (CEO) for each company? This would decrease the sample size from 8926 to 1703 observations, but it would ensure that all of my observations are truly “unique”. Thank you very much!

**Comment by IvovanZitteren** [comment]
Perhaps I should add that my database includes dummies for the CEO and CFO of each company. The other 3 executives of all companies have varying roles/titles.

**Comment by janboone** [comment]
It is not necessarily a problem that executives from the same company have the same company characteristics; you can still use them to find the effect of e.g. age on compensation. So executives within a company are unique on some (but not all) dimensions.

Is there are also a time dimension to the data? Then with a change in CEO there will be different company variable values for the CEO role.

**Comment by IvovanZitteren** [comment]
There is no time dimension in my data. Thank you very much for the answer!
