### ISSUE TITLE
Problem with joining team in GitHub classroom

### ISSUE THREAD

**Issue by SamHamers** [janboone/msc_datascience#15]
Hi,

I'm running into a problem when trying to join a team in GitHub classroom. It happens both on Chrome and Firefox. After I create my team (Team Sam), I get the following message:

> "You accepted the assignment, final-assignment-2021 . We're configuring your repository now. This may take a few minutes to complete. Refresh this page to see updates."

However, after about 10 minutes, it changes to the following message:

> "You accepted the assignment, final-assignment-2021 but something went wrong. We have not received any updates for this assignment. You may want to reaccept the assignment."

If I try to reaccept the assignment, I get returned to the first message which then fails again after a few minutes. I hope you can help me with this issue.

Moreover, I also wondered how I should upload my assignment which I created entirely in R. Should I remove the file named assignment_notebook.ipynb and upload a new file named assignment_notebook.rmd?

**Comment by janboone** [comment]
I can see your team-repository for AEA, but indeed not the one for datascience. Your team for AEA is "team_sam", not "team sam" but I don't think this is the issue.

Can you try again from a private tab in firefox?

Indeed, you can remove the ipynb file and replace it with the rmd file.

Let me know if this does not work.

Jan.

**Comment by janboone** [comment]
ik zie dat het gelukt is.
