### ISSUE TITLE
Uploading big file to Github

### ISSUE THREAD

**Issue by SilviaGib** [janboone/msc_datascience#16]
Dear professors,

I am trying to upload the data I used for the final assignment (or its zipfile). However, when I try to do it in GitHub it says the file is too big and should be under 25MB.  I tried to follow this guide but it's not working for me https://evidencen.com/how-to-upload-large-files-100mb-to-github/
What should I do? Can I send you my data via email or another method?

Thank you!

Silvia

**Comment by janboone** [comment]
Hi Silvia,

In that case you can use https://wetransfer.com/ to share the data.

Regards,

Jan.

**Comment by SilviaGib** [comment]
Okay, I will do that. Thank you very much professor!

Best,

Silvia
