### ISSUE TITLE
GARCH models

### ISSUE THREAD

**Issue by Luisa2019** [janboone/msc_datascience#2]
Dear Medina and Jan,

For this assignment I am working on time series.
I am implementing a GARCH model using the data from the electricity wholesale market from 2005 to 2019, I have hourly observations for the different countries in the Nordic market. 
I am modeling volatility with GARCH, while taking into account a policy change in November 2011. Is that sufficient for the assignment? Should I also implement a data mining analysis?
Thank you!
Luisa Loiacono

**Comment by janboone** [comment]
Hi Luisa,

There is nothing wrong with a GARCH, but we would like to see elements of the course coming back in your assignment. This can be in the way you handle and clean the data, simulations to understand the properties of the GARCH etc.

Put differently, just using the data that you have and running a GARCH in stata would not be sufficient.

Does this help?

Jan.

**Comment by Luisa2019** [comment]
Yes, thank you very much for your response.
Sorry for the late reply.
Luisa Loiacono
+39 3332999189 | luisa.loiacono@unipr.it  <luisa.loiacono@unipr.it>
** Think about the environment before printing.*
