### ISSUE TITLE
Cannot import package tensorflow

### ISSUE THREAD

**Issue by PaulMaasdijk** [janboone/msc_datascience#21]
Hello Jan,

I can't import the package tensorflow. it gives the following error : No module named 'tensorflow'

I tried to the following code that also didn't work 
%%bash

pip install --user tensorflow

I got this error: Command 'b'\npip install --user tensorflow\n'' returned non-zero exit status 137.

**Comment by SkirmantasD** [comment]
I also have the same issue of installing tensorflow in Jupyterlab. Have tried multiple solutions from Google, but without any success.

**Comment by janboone** [comment]
can you email me your student numbers? I will ask IT what the problem is on your jupyterlab accounts.

**Comment by Jonasbrouw99** [comment]
I have the same issue with installing tensorflow in Jupyterlab.

**Comment by janboone** [comment]
IT has informed me that this problem has been solved by now. There is no need to install tensorflow yourself.
