### ISSUE TITLE
assignment 1

### ISSUE THREAD

**Issue by Bramh1998** [janboone/msc_datascience#22]
excuses, ik had dit ook al op mail gestuurd maar dit leek me een stuk effectiever aangezien ik graag wil beginnen aan de opdracht.

Ik had even een vraag naar u over de seminar data science voor economics. Ik moest dit studiejaar nog maar 2 vakken afronden dus hiernaast ben ik full time gaan werken. Ik heb komende 2 weken vrij gevraagd zodat ik voldoende tijd heb voor het afronden van de final assignment, ook omdat ik al aardig wat ervaring heb met python is dit zeker haalbaar. Echter vroeg ik me af of ik assignment 1 op tijd had ingeleverd, ik kan me zeker herinneren dat ik de form had ingevuld echter leek het me een goed idee om dit even bij u na te trekken aangezien ik de opdracht anders voor niks ga zitten maken. Bij voorbaat dank & excuses voor het ongemak.

Met vriendelijke groet,
Bram Heijstek

**Comment by janboone** [comment]
Hallo Bram,

Geen probleem, je kunt met de assignment aan de slag. 

Als je de assignment inlevert (via github) moet je ook weer een google formulier invullen: 

https://janboone.github.io/msc_datascience/#orgb4d7806

Groet,

Jan.

**Comment by Bramh1998** [comment]
Beste meneer Boone,

Ten eerste, fijn om te horen dat ik met de assignment aan de slag kan. Ik had echter nog een vraag, mijn research question is 'Does inflation have an affect economic growth, and, does this effect vary for democratic countries compared to non-democratic countries ?'. De data voor economic growth & inflation haal ik van World bank af, echter is een goeie Democracy indicator vinden wat ingewikkelder. Acemoglu et al. (2019) had in hun paper 'Democracy does cause growth' een goede manier gevonden om een democracy indicator samen te stellen & de resultaten hiervan zijn ook beschikbaar https://www.journals.uchicago.edu/doi/abs/10.1086/700936?mobileUi=0& . Mijn vraag voor u is dus of ik toestemming heb om deze data voor de democracy indicator te gebruiken. 
Met vriendelijke groet,
Bram Heijstek

**Comment by janboone** [comment]
is prima om die te gebruiken.

Groet,

Jan.
