### ISSUE TITLE
Doubt regarding choosing variables/confounders

### ISSUE THREAD

**Issue by 211sk** [janboone/msc_datascience#23]
Hello Jan, 

We (Pranav and Raphaela) are making our python project for the resit submission. We are writing you for approval of our dataset (as mentioned on the webpage) and for doubt regarding our topic.  

We are working with the varieties of democracy (VDem - https://v-dem.net/vdemds.html codebook - https://www.v-dem.net/static/website/img/refs/codebookv12.pdf ) dataset. The dataset makes an assessment of a country’s democracy levels through several indicators and variables. The question we explore is “Which political factors predict corruption levels in a country?” For this, we use the article Predicting and explaining corruption across countries: A machine learning approach (Lima & Delen, 2020) as a reference. We have two questions in this regard -  

We plan to use mid-level indices which answers a variety of questions about democracy. A lot of these variables have common source factors (like free and fair election), so do we use source factors, or will it be okay if we use these mid-level indices? 

Corruption can be confounded or forked with economic variables like GDP. How do we account for them? Do we control for them or leave them be? Is there a way we can check it? 

We are using random forest and lasso regression to find out the most important factors that predict corruption. We are focusing on predicting and not causality.

 
Could you please guide us on these questions, where can we look for the answers, or in which direction should we think? 

 

Thanking you in advance 

Pranav and Raphaela

**Comment by janboone** [comment]
Hi Pranav and Raphaela,

- mid-level indices are fine with me
- if theory suggests that (low) gdp affects corruption in addition to how governance is organized (e.g. democracy), then gdp needs to be added as a variable.

Does this help?

Jan.

**Comment by 211sk** [comment]
Yes, just one follow up question on mid-level indices. There is a lot of overlap between some of these variables. Is there something that we have to before we directly put them into the models (random forest/lasso), or will the model be able to handle those correlations?

**Comment by janboone** [comment]
it depends what you mean by "handle those correlations". If the correlations are too high, the model will be multi-collinear and cannot be estimated. In that case you will have to drop some variables.

The correlations will make it hard to interpret the results (what is causing which effect). But as you are (only) interested in prediction (not causality) that should be less of an issue.

**Comment by 211sk** [comment]
Thank you, and yes, we are more concerned about prediction than causality. We will check for correlation levels first then using VIF before proceeding

**Comment by 211sk** [comment]
When I was going through the assessment material, it said to use either "Machine learning (eg. Neural Network) or Bayesian estimation. Just to confirm, if it is alright to use machine learning techniques like random forest, gradient boosting and lasso. We are using them to compare their predictions, but the project does not contain an explicit use of neural networking or bayesian techniques. Would that be okay?
