### ISSUE TITLE
Confirmation of the method that can be used for the project

### ISSUE THREAD

**Issue by 211sk** [janboone/msc_datascience#25]
When I was going through the assessment material, it said to use either "Machine learning (eg. Neural Network) or Bayesian estimation. Just to confirm, if it is alright to use machine learning techniques like random forest, gradient boosting and lasso. We are using them to compare their predictions, but the project does not contain an explicit use of neural networking or bayesian techniques. Would that be okay, or will using it impact our performance/grade in the project?

**Comment by janboone** [comment]
Apologies for my late reply: I was on holiday.

The idea of the assignment is that you show us what you learned during the course. The more you show us of different things you have learned, the higher your grade.

I hope this helps to explain how we grade the assignments.
