### ISSUE TITLE
Error while running pymc model

### ISSUE THREAD

**Issue by lparisi94** [janboone/msc_datascience#26]
Dear Jan,

While running a Bayesian model my Jupyter notebook breaks. I will attach the image of the error message.

I have ran this code before and it worked. Furthermore, my group colleague has also been running this code and everything works fine for him.

I have tried googling this problem for days and nothing has worked.

![Error_Python](https://user-images.githubusercontent.com/98168796/183225440-2d281062-ebe6-4b78-aed1-c651afdc1144.PNG)

Thank you,

Luka Parisi

**Comment by janboone** [comment]
Apologies for my late reply: I was on holiday.

It seems weird that the code ran before and now gives errors. Can you restart the kernel and run the notebook. Does it work now?

**Comment by lparisi94** [comment]
For some reason, this error persists only on my personal laptop, while the code works on other computers. Is there some way to completely reboot/reinstall from scratch Jupyter notebook/Anaconda?

**Comment by janboone** [comment]
Indeed, you can uninstall anaconda and then install it again from https://www.anaconda.com/products/distribution

Perhaps something went wrong with the versin on your laptop.
