### ISSUE TITLE
Deadline 26th of august

### ISSUE THREAD

**Issue by Bramh1998** [janboone/msc_datascience#27]
Beste meneer Boone,
Ik wil u graag verzoeken voor uitstel van de laatste deadline, ik zou het begrijpen als dit niet mogelijk is maar ik zal u uitleggen waarom ik dit verzoek. Ik ben eigenlijk heel de zomer weg / aan het werk geweest & had deze week initieel ingepland om de herkansing te maken. Echter kon ik door onvoorziene omstandigheden pas later terugreizen uit Mexico waardoor ik maandag pas terug was, verder kwam ik thuis waar vrijwel iedereen ziek was. Hierdoor ben ik uiteindelijk ook 2 dagen onder zeil geweest. Door bovenstaand houd ik eigenlijk nog maar 2 dagen over voor het maken van de herkansing, ik zou het begrijpen als u geen uitstel kunt verschaffen maar zou het prettig vinden als u dit wel overweegt. Bij voorbaat dank & ik kijk uit naar uw reactie

**Comment by janboone** [comment]
Ik kan niet zelf uitstel verlenen. Dat loopt via de education coordinator van de MSc Economics. Als zij akkoord is met uitstel, is dat voor mij ook goed.
