### ISSUE TITLE
Bayesian Statistics: Handling missing data for wind speed measurements with time dimension

### ISSUE THREAD

**Issue by nikolaijaeger** [janboone/msc_datascience#31]
Dear Jan Boone,

Our objective is to predict hourly wind energy generation using hourly wind speed measurements from over 400 weather stations. We have a question regarding the handling of missing data. As you have noted, simply eliminating variables with missing data is not an ideal strategy. 

To address missing data, we're considering retaining all stations with at least 95% data availability. This ensures that the majority of our dataset consists of observed values, which carry lower uncertainty than imputed ones. For the stations with up to 5% missing data, our initial approach is to utilize K-nearest neighbors for imputation in OLS and Ridge/Lasso models. For our Bayesian model, we currently draw from the normal wind speed distribution.

However, given the sequential nature of wind speed data: the speed this hour is influenced by the speed from the previous hour, sampling randomly from the wind speed distribution might not capture this temporal dependence. We looked at Gaussian Process methods as explained in the "Statistical Hacking Part 2" notebook. However, those examples focus on time series, where the explanatory factor is time. In our model, we would like to account for both time dependency and wind speed.
Given these considerations, do you have recommendations on how we can refine our approach to address missing values more effectively? Or would you suggest that we proceed with the independent sampling technique introduced in the course?  Thank you very much!

Kate and Nikolai

**Comment by janboone** [comment]
Indeed, for the assignment it is perfectly fine to use the independent sampling technique we used in the course.

If you want to do something more sophisticated, you could define two new columns for your data: the first column --say $x_1$-- is for each observation the last observation available. So if you have data for this station and hour, $x_1$ equals this observation. If you do not have an observation for this hour but the last observation is from 2 hours ago, $x_1$ equals this last observation.

The second column -- $x_2$ -- denotes the time period till the last observed value. Hence, if you have an observation now, we have $x_2 = 0$. If the last observed value is from 2 hours ago, $x_2 = 2$.

Then when specifying the distribution from which to draw missing values specify a mean equal to $x_1$ and a standard deviation related to $x_2$. That is, the standard deviation increases as $x_2$ gets bigger. You can use your data to calibrate what a reasonable function is for the standard deviation to increase with each hour.

This approach (which is *not* necessary for the assignment) takes some of the time dependencies that you mention into account without going for a full blown (GP) model.

Does  this help?

Jan.

**Comment by nikolaijaeger** [comment]
Thank you very much, this is very helpful!
