### ISSUE TITLE
Posterior Predictive Intervals for Outcome Variable Are Stable

### ISSUE THREAD

**Issue by nikolaijaeger** [janboone/msc_datascience#32]
![Log_Transformed_standardized](https://github.com/janboone/msc_datascience/assets/112488976/008a3e33-ce94-493b-a4f1-75e5f526a741)
![Just_standardized](https://github.com/janboone/msc_datascience/assets/112488976/115a12c4-9a0e-433c-a2a3-c3ed82c7f10d)

Independent of the priors we set, the bayesian model estimates intervals for our outcome variable that seem not to depend on the wind speed (two example weather stations in the graphs). We thought also it might come from the distribution of wind speed which has some very high values. But also for the case of a log transformation, the intervals do not include the actual observations. Is there a specific reason for this that hints to a wrong model? In our view the rest of the model runs smoothly and produces reasonable coefficient distributions.

**Comment by janboone** [comment]
this looks a bit strange, indeed. Can you send me the code (by email if that is easier) for this part of the model?
