### ISSUE TITLE
Question about DataCamp access

### ISSUE THREAD

**Issue by u876834** [janboone/msc_datascience#5]
I am working on the course statistical simulation in Python and it asked me to upgrade my account to continue the course. How can I resolve this?

**Comment by janboone** [comment]
did you register on datacamp via https://www.tilburguniversity.edu/students/skills/programming

If not, do this first.

If you have registered, perhaps you have another datacamp account on which you are logged in which does not give you access to all courses for free. If so, log out and then log in again using your TiU datacamp account.

Does this help?

**Comment by u876834** [comment]
It works after sending an email to library-scienceskills@tilburguniversity.edu.
