### ISSUE TITLE
Question about broadcasting

### ISSUE THREAD

**Issue by yannikobeloer** [janboone/msc_datascience#6]
I have a question about the last exercise of the section on broadcasting. I understand that for instance (10,10) + (50,2,1) cannot be broadcasted together as in the example on numpy.org where the second from last dimension is mismatched. As shapes (10,10) + (100,1,1) may be broadcasted, does this mismatch of dimensions generally not apply to cases where the dimension is = 1?

**Comment by janboone** [comment]
Indeed, you can always broadcast when a dimension equals 1 for one of the tensors.
