### ISSUE TITLE
Question about Bootstrapping

### ISSUE THREAD

**Issue by BarboraPisecka** [janboone/msc_datascience#8]
In the Screencasts, section Bootstrapping, you use the following command:

"np.random.shuffle(AB)"

However, isn't that permutation testing? For bootstrapping, shouldn't we allow for replacement? 

Thank you in advance!

**Comment by janboone** [comment]
The command `np.random.shuffle(AB)` only shuffles the elements in the vector `AB`; it does not draw samples yet. The next line of code actually draws the sample with `AB[:sample_size]` and `AB[sample_size:]`.

You are correct that these samples are drawn without replacement in the sense that a given observation can only be drawn once in the way we model it here.

Drawing 50 samples with replacement from `AB` to form sample `A` and then drawing 50 samples with replacement to form sample `B` is also fine, of course.
